#!/bin/bash

# Quick Git & Database Commands
# Copy and paste these commands as needed

echo "FarmFeed Git & Database Commands"
echo "=================================="
echo ""
echo "Choose what you want to do:"
echo ""
echo "1. PUSH to GitHub (First Time)"
echo "   git remote add origin https://github.com/YOUR_USERNAME/FarmFeed.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "2. PUSH Code Changes"
echo "   git add ."
echo "   git commit -m '[TYPE] Your message'"
echo "   git push origin main"
echo ""
echo "3. PUSH Database Changes"
echo "   mysqldump -u root -proot FarmFeed > DB/farmfeed_db_backup.sql"
echo "   git add DB/farmfeed_db_backup.sql"
echo "   git commit -m '[DATABASE] Updated schema'"
echo "   git push origin main"
echo ""
echo "4. PULL Latest Code (Team Members)"
echo "   git pull origin main"
echo ""
echo "5. PULL Latest Code & Database"
echo "   git pull origin main"
echo "   mysql -u root -proot FarmFeed < DB/farmfeed_db_backup.sql"
echo ""
echo "6. CLONE Repository (New Team Member)"
echo "   git clone https://github.com/YOUR_USERNAME/FarmFeed.git"
echo "   cd FarmFeed"
echo "   mysql -u root -proot < DB/farmfeed_db_backup.sql"
echo "   cd farmFeed && java -jar target/farmfeed-1.0.0.jar"
echo ""
echo "7. CREATE Feature Branch"
echo "   git checkout -b feature/your-feature-name"
echo "   # Make changes..."
echo "   git add ."
echo "   git commit -m '[FEAT] Feature description'"
echo "   git push origin feature/your-feature-name"
echo ""
echo "8. VIEW Commit History"
echo "   git log --oneline"
echo ""
echo "9. CHECK Git Status"
echo "   git status"
echo ""
echo "10. RESET to Latest (Discard Local Changes)"
echo "    git fetch origin"
echo "    git reset --hard origin/main"
echo ""
