# Application
spring.application.name=FarmFeed

# Server
server.port=${PORT:9090}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/farmfeed}
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=validate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable open-in-view for production
spring.jpa.open-in-view=false